# Generated by Django 6.0.5 on 2026-06-02 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sabor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, unique=True)),
                ("codigo", models.CharField(max_length=120, unique=True)),
                (
                    "precio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "costoInsumos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("estado", models.BooleanField(default=True)),
                (
                    "sabor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="heladeria.sabor",
                    ),
                ),
            ],
        ),
    ]
